name: Tests
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: ruudjhuu/freecad:v1.0.0-2
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: python -m unittest discover tests -v
  freecad-tests:
    runs-on: ubuntu-latest
    container: ruudjhuu/freecad:v1.0.0-2
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Add workbench to FreeCAD
        run: |
          mkdir -p $HOME/.local/share/FreeCAD/Mod
          ln -s $PWD $HOME/.local/share/FreeCAD/Mod/Gridfinity
      - name: Run freecad tests
        run: |
          set -o pipefail
          xvfb-run freecad -t freecad.gridfinity_workbench.test_gridfinity 2>&1 | tee output.txt
      - name: Check caught exceptions
        # FreeCAD catches exceptions during command invocation and only shows them in GUI, exiting with 0
        # This makes the some tests pass when they shouldn't, so we look for the exceptions here
        run: "! grep -B 1 Traceback output.txt"
